name: yoshlar
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  logger: ^2.6.2
  http: ^1.6.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  bloc: ^9.2.0
  fluttertoast: ^8.2.4
  http_parser: ^4.1.2
  shimmer: ^3.0.0
  permission_handler: ^12.0.1
  easy_search_bar_2: ^1.0.0
  image_picker: ^1.0.7
  google_nav_bar: ^5.0.7
  flutter_staggered_animations: ^1.1.1
  fl_chart: ^0.70.0
  flutter_secure_storage: ^9.2.4
  geolocator: ^13.0.2
  url_launcher: ^6.2.5
  web: ^1.1.1
  excel: ^4.0.6
  file_picker: ^8.0.0

  ###### awesome_dialog: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6


flutter:


  uses-material-design: true


  assets:
    - assets/images/


